language: node_js
node_js:
- 10
branches:
  only:
  - master
install:
  - yarn
  - CI=false yarn build:ssr
  - yarn fns:deps
#after_success:
#  - node_modules/.bin/firebase deploy --non-interactive --token "$FIREBASE_TOKEN" --project react-joanne
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "yW+0KKbJr2r5mwMQ4KsOBWh6oZF6HXtGPS0nsMND4kXKORjcLJlkW36bLj35FDWR49crQDedK6/jK1aAWttcFJJvGpEaBANMSqpRYhwhgj6dumAy0lM38J0ikx+pgE4ZvTp8KtwH7CzBFn8lIabBJUOJsbQdZlHLFx/EijEbydRspTC62QAv9ri/eKPBvIJnB58kQq8B2ayA7jek/bwOvA+Rg87F4CZ8rWxonGtEle2mEHwuC3Z7CNHLQRyIHidMmMhXt8pwmG1dIVbib6m+dn8bKHhdbnpjM90GYoLrOgfrd451BardpTgU3woJu2AI7Ugn2aefsjl1L3uJof34fM385Kk2iyKv2pBB/ZH6V1nOWJ3TkWu6946AHr4n0jmAe2Pxlsbv60adkLuLclNHQo1H0GQrqU+3bPdBwCe5Fw8Lly6K+BrWSLDzmy8IQXAFn6X+MCzaL8k+LGwmQJuqqblmqw2OJALkgS/mkBAEdtb5pC120W5pmlQpxvbxmCsxCzQmr11JKPYtPaUWOGcpdjk0erfJ9vjiTB1ASDtafJKbffJiVs/OMZ6XPKdQdGyDYwu/NGx+kKhNahS/Qthgtkg5yekFKp3PQNUH7AL4YMqgaKslDJ5+hSJe4hxTcLZrXZrpBOwglulyQhMW2zYwtKD2159l4w4ZUNW3VwJwkb0="
  project: "react-joanne"