language: node_js
node_js:
- 10
branches:
  only:
  - master
install:
- yarn
- CI=false yarn build:ssr
- yarn fns:deps
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: hnJfgzzSY2asWNdFxesUL9xVGylQYpE9sPGX/P8GyLbnCplzLSjFNdQLYHTXbXwDOW+mn641U1BONufqoXxDHW6oiYn3g0Nolt9TTHi0/LY3Nu5x2eRd3obVm0JQRRggFVcORQmkLtlkW/LBUwufYG8jNCLXI3LYbK8HPDBwl2Wx7/hwHIRh0DFnYurH52PETDUa4BGiTwt3A4pixCe9171bDeoUCmLuhZiiFPOVW+bhWQcYTcFIyvC9Fm1HBOzXSpiOXmAB2nJ6oZtELcMTmTGpyS7zYOGbT8VgmZfKVg28vPGtejiBglkhXQ7jKQYQbrbGiQ8G5y6rU4VlK3u/x5PdU3Z5E9EK/GIxJZFPKBAxOBrGdMKkb3ZFEBKs0lZtGoVuW58RgLcQ8ZmT6v9QSApP4kXT22R+kJp26dPz3t9LpdB+YiHGzVTmWvPE06h+/6iB2lTufaMC1GIWQanF57KcEbsMs5a82gg8o044ZgdiVKFBvpQIdAQVapBC6CydCFODpv2lc3315ot/HKH8KaHYIQLssRM3RynoN0OUiJ+Hsx798a1xrAQrxz0OrzeGsMFxR9ZTJN0VUMB0zV5hQEasRBIf51xWAAzDoLDF1AwKm/9/ZXqgO8SUsVLHFWYwOOo/g22ILDpEQJzDgvf7ohzrFV1J0RfjyXXx62xrlBs=
  project: react-joanne
